### ISSUE TITLE
Translate README into English

### ISSUE THREAD

**Issue by mbenford** [globocom/prettylog#1]
The README file should be translated into English so it reaches a wider audience.

**Comment by akosasante** [comment]
👋 Hello, I'm happy to manually translate this; though I am also wondering whether it would be worthwhile to use some sort of i18n plugin/tool to do so instead?

**Comment by mbenford** [comment]
Hi. If you happen to speak Portuguese then a manual translation would be best. But if you know a tool that is good enough, I guess you could give it a try. :)

**Comment by willkraemer** [comment]
I'd like to work on this issue, could you assign it to me please? 
I also have a question, the ideia behind this issue is to change the README file content to english, or keep the portuguese content and add an english translation?

**Comment by osmarpetryzup** [comment]
@akosasante  Are you already doing this?

**Comment by akosasante** [comment]
I have not yet started; I was planing on trying to use an internationalization tool but if either you @osmarpetryzup / @mbenford  have a better understanding of Portuguese, feel free to take this 👍 😄

**Comment by n8eloy** [comment]
I'm currently working on it! 😃

**Comment by amintasvrp** [comment]
I did a pull request to this repository. But, it may be interesting to keep both versions: in Brazilian Portuguese, because is the main language of the Globo group , and English.
