### ISSUE TITLE
Set up CircleCI configuration

### ISSUE THREAD

**Issue by rafaveira3** [globocom/prettylog#7]
We could use CircleCI to add stages to be run on every push made to the project. Starting with `make test` would be a good idea, what do you think? I could help with that. 🐼

**Comment by mbenford** [comment]
Continuous integration is never a bad idea. :) Feel free to work on it, if you want to.

**Comment by rafaveira3** [comment]
Awesome! I can work on this one! Would you mind providing me access to the repository so I can set up CircleCI? I guess Developer role is good enough for that!

**Comment by mohitsaxenaknoldus** [comment]
Can I work on this for Hacktoberfest @mbenford ?

**Comment by mbenford** [comment]
@mohitsaxenaknoldus This issue is outdated since GitHub Actions exists. I appreciate you interest in helping, though. 😃
